### ISSUE TITLE
Some institutions tests are failing due to second password

### ISSUE THREAD

**Issue by midito** [belvo-finance/belvo-python#60]
#### Issue description

Tests are returning errors for institutions that use the second password

#### Steps to reproduce the issue

...

### Environment used?
Staging

#### What's the expected result?
Link successfully created

#### What's the actual result?
banregio_mx_retail in 0.16s
• :x: Create Link: [{'field': 'password2', 'message': 'This field may not be blank.', 'code': 'blank'}, {'field': 'username_type', 'message': 'This field may not be null.', 'code': 'null'}]

#### Additional details / screenshot
Related? Hector reported me last Thursday that belvo-python in pypi was not updated and it could generate errors in institutions requiring password2 using python library, like this one or bradesco.

**Comment by shekodn** [comment]
Hey @hecrogon  

I have a question: Why `banregio_mx_retail` is not [here](https://github.com/belvo-finance/scraper_tester/blob/df4d4e7027a124f594bcac49e7a92a13d9e3d1ed/import_test_data.py)? Also, do you know if it is possible to pass `None`, instead of `""` to the test? According to @bmagnan in [this thread](https://belvo.slack.com/archives/C015Q7VGC3D/p1598037225012000) this bank shouldn't have two passwords. 

Besides, password2 is behaving as expected since null is allowed. https://github.com/belvo-finance/public_api/blob/fda17d7d42a2f6d0ee13f91519d6f6169fc2c814/src/api/links/models.py#L48


cc. @midito

**Comment by bmagnan** [comment]
The issue has been resolved. There was a null value for a password2 in the
database for this banregio test.
